server:
  port: 8088

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/testrestful
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    user:
      name: username
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"

